### PR TITLE
session identifier

### PR DESCRIPTION
**Pull request by andrei-egeniq**
https://github.com/SURFnet/nonweb-sso-android/issues/8

### CODE REVIEW

**Comment by welsinga** [comment]
Not really feature branching? Also first to developer please.

**Comment by dzolnai** [comment]
I see now that we don't handle activity recreation, so this will fail if the device is short on memory.
We should store the private values of the activity in a bundle, because launching the browser and then coming back to the app may easily recreate the activity on older devices.

**Comment by andrei-egeniq** [comment]
@dzolnai the callback reference would be lost on activity recreation. Another trigger will be needed.

**Comment by dzolnai** [comment]
@andrei-egeniq I don't think so, it is static.

**Comment by andrei-egeniq** [comment]
On low memory, the application is killed. All of it. Every single object. As far as I know, when recreated, static objects are null. Can be tested.

**Comment by dzolnai** [comment]
On low memory, the activity views are destroyed, and state is saved into bundle.
The class instance is deleted, but the JVM of the app is kept alive, so static variables are unchanged.
On very low memory, the entire application is killed, as you said.
Please test it with that debug option "Do not keep activities"

**Review by dzolnai — APPROVED** [review]

**Pull request merged**
